// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import { Inter, Instrument_Serif } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const serif = Instrument_Serif({ subsets: ['latin'], weight: '400', variable: '--font-instrument-serif' });
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className={`${inter.variable} ${serif.variable}`}>
        <body className="relative bg-primary px-7 py-7 h-screen">
            <Navbar />
            <div>
              {children}
              </div>
        </body>
      </html>
    </>
  );
}
