import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="relative  bg-primary px-5 lg:px-7 py-7 min-w-[360px] overflow-x-hidden">
            <Navbar />
            <div className="">
              {children}
          </div>
          <Footer/>
        </body>
      </html>
    </>
  );
}
